### ISSUE TITLE
Features PATH error

### ISSUE THREAD

**Issue by risknu** [sentemon/GeometryCalculator#1]
```
Unhandled exception. System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Users\mac\Desktop\GeometricCalculator\GeometricCalculator\BaseClasses\Shapes'.
   at System.IO.Enumeration.FileSystemEnumerator`1.CreateDirectoryHandle(String path, Boolean ignoreNotFound)
   at System.IO.Enumeration.FileSystemEnumerator`1.Init()
   at System.IO.Enumeration.FileSystemEnumerable`1..ctor(String directory, FindTransform transform, EnumerationOptions options, Boolean isNormalized)
   at System.IO.Enumeration.FileSystemEnumerableFactory.UserFiles(String directory, String expression, EnumerationOptions options)
   at System.IO.Directory.InternalEnumeratePaths(String path, String searchPattern, SearchTarget searchTarget, EnumerationOptions options)
   at System.IO.Directory.GetFiles(String path, String searchPattern, EnumerationOptions enumerationOptions)

   at GeometricCalculator.Features.WriteShapes() in C:\Users\risknumak\GeometricCalculator\GeometricCalculator\Feauteres.cs:line 103
   at GeometricCalculator.Program.Main(String[] args) in C:\Users\risknumak\GeometricCalculator\GeometricCalculator\Program.cs:line 17
   ```

**Comment by risknu** [comment]
```cs
public static void WriteShapes()
{
    string pathOfShapes = "/Users/mac/Desktop/GeometricCalculator/GeometricCalculator/BaseClasses/Shapes/";
    string[] shapesName = Directory.GetFiles(pathOfShapes);

    for (int i = 0; i < shapesName.Length; i++)
    {
        shapes.Add(i + 1, shapesName[i]
            .Replace("/Users/mac/Desktop/GeometricCalculator/GeometricCalculator/BaseClasses/Shapes/", "")
            .Replace(".cs", ""));
    }
}
```

**Comment by risknu** [comment]
```cs
public static void WriteShapes()
{
    string directoryPath = Path.Combine(Environment.GetFolderPath(Environment.SpecialFolder.UserProfile), "GeometricCalculator/GeometricCalculator/BaseClasses/Shapes");
    if (Directory.Exists(directoryPath))
    {
        string[] files = Directory.GetFiles(directoryPath);
        for (int i = 0; i < files.Length; i++)
        {
            string fileNameWithoutExtension = Path.GetFileNameWithoutExtension(files[i]);
            Console.WriteLine($"{i + 1} {fileNameWithoutExtension}");
            shapes.Add(i + 1, fileNameWithoutExtension);
        }
    }
    else
    {
        Console.WriteLine("Directory does not exist.");
    }
}
```

**Comment by sentemon** [comment]
thx
